<a href="https://colab.research.google.com/github/mail2chandanadasari-code/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Numpy in Python

In [5]:
import numpy as np


Numpy Array Creation

In [4]:
# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [6]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)


[2 4 6 8]


**Create a 2-D Numpy Array**

In [7]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


**Create a 3-D Array**

In [13]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [15]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)




int64


**Check dimensions of an Numpy Array**

In [16]:
print(array1.ndim)


1


**Check Size of Numpy array**

In [17]:
print(array1.size)


3


**NumPy Array shape Attribute**

In [18]:

array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)


(2, 3)


**NumPy Array itemsize Attribute**

In [19]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4
